
import boto3
import numpy as np
import json
import joblib

client = boto3.client('sagemaker-runtime')

inference_data = [291, 97, 41, 9, 0.82, 22.56]

scaler = joblib.load('./local/scaler.gz') # This file will be generated by preprocessing job and will be in sagemaker s3 default bucket.

data = np.array(inference_data)
print(data)

data = data.reshape(1,5) # scaler requires 2D array
data = scaler.transform(data)
data = data.reshape(5,) # let's get our 1D array back

data = ",".join(map(str, data)) # convert to csv format

print(data)

response = client.invoke_endpoint(
    EndpointName='kmeans-2020-05-16-03-23-14-106',
    Body = data,
    ContentType='text/csv',
)

result = json.loads(response['Body'].read().decode())

print(result)



